nelmio_cors:
    defaults:
        allow_origin: ['*'] # Autoriser toutes les origines, à modifier si besoin
        allow_headers: ['content-type', 'authorization']
        allow_methods: ['GET', 'POST', 'PUT', 'DELETE', 'OPTIONS']
        max_age: 3600
    paths:
        '^/api/': # Appliquer les CORS uniquement aux routes commençant par /api/
            allow_origin: ['*']
